controllers:
    resource: '../src/Controller/'
    type:     annotation

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#
#ingredient_index:
#    path: /ingredient
#    controller: App\Controller\IngredientController::index
#
#ingredient_new:
#    path: /ingredient/new
#    controller: App\Controller\IngredientController::new
